services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    #    command: --serviceExecutor adaptive
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisdb:/data

volumes:
  mongodb:
  redisdb:

  